# Generated by Django 4.2.6 on 2023-10-29 07:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('order', models.PositiveIntegerField(verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ToDoUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('handle_name', models.CharField(max_length=255, verbose_name='表示名')),
            ],
            options={
                'verbose_name': 'ToDoUser',
                'verbose_name_plural': 'ToDoUser',
                'ordering': ['-date_joined'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('deadline', models.DateTimeField(verbose_name='締め切り')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('priority', models.PositiveIntegerField(choices=[(1, '高'), (2, '中'), (3, '低')], verbose_name='優先度')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('categories', models.ManyToManyField(to='todo.category', verbose_name='カテゴリー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.todouser', verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDo',
            },
        ),
    ]
